const ActionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    CREATE_PARCEL_SUCCESS: 'CREATE_PARCEL_SUCCESS',
    CREATE_PARCEL_FALIURE: 'CREATE_PARCEL_FALIURE',
  };
  
  export default ActionTypes;
  export const PARCEL_FETCH_NOT_FOUND = 'PARCEL_FETCH_NOT_FOUND';
  export const PARCEL_FETCH_SUCCESSFUL = 'PARCEL_FETCH_SUCCESSFUL';
  export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
  export const LOGIN_FAIL = 'LOGIN_FAIL';
